### ISSUE TITLE
Bug? (with the latest Sketch update)

### ISSUE THREAD

**Issue by pandasaurusrex** [srbsingh3/autoarrange#1]
First, your plugin is a godsend -- thank you so much for creating it! It's especially helpful now that my team is using Abstract, which displays assets according to their position in the layers list.

I recently updated to Sketch 55.1 and am using Abstract 80.0.1 in tandem with it. After the update, I noticed that whenever I run Autoarrange (the latest version, 1.0), it also rearranges artboards on the canvas itself, instead of just shuffling the order of the artboards in the layers list. (Hopefully this is only affecting artboards... I haven't looked closely enough to see if layers _within_ artboards are also getting moved around on the canvas.) Previously, the plugin only affected the layers list and not the actual positions of things on the canvas, which is the desired behavior.

Is this a known reproducible bug and would a fix be in the works? 

Thank you!!

**Comment by srbsingh3** [comment]
Hi @pandasaurusrex. Thank you for your kind feedback.

Actually, I have put in a little hack in my code where the plugin aligns the artboards on the canvas before re-arranging their order in the layer list. I was not able to figure out a way to effectively arrange the list order if the artboards aren't aligned properly on the canvas. I tested it with a bunch of combinations and it wasn't moving the artboards too much on the canvas. I hope it doesn't do any harm in your case. And don't worry, my code never re-arranges individual layers.

I hope this helps.
